### ISSUE TITLE
problem with the downloader 

### ISSUE THREAD

**Issue by boostrrr** [ab-anand/ZDrive#3]
ZDrive is one of the best programs ive ever seen, but I think I got a little bug or something like this! I coded a Gui, that runs the uploader or downloader script when I press a button. The uploader works fine, and I can upload folders with only one click, but when it comes to the downloader I got a problem. When I run the Gui in python, and click the button, the window frezzes and opens up itself again, so that I have the frozen window and a working window, that also frezzes when I click the button in the new Window, and opens up itself again. I was able to fix this error by using a codeline that makes sure that no new prozess is started while anotherone is still running. With this quick fix everything works fine when I run the programm in python, but when I compile it to an exe and run this exe, I have the same error again, the window frezzes after clicking the button and open itself once again. 
Im messing with this now since Yesterday, and really dont know what I could do. 
I would appreciate any answer

**Comment by ab-anand** [comment]
It would have been helpful if you could provide steps to reproduce the code or your code repo link and the OS you're using.

However, with the given info I think this should resolve the issue:
https://stackoverflow.com/questions/18204782/runtimeerror-on-windows-trying-python-multiprocessing
