### ISSUE TITLE
Doesn't download all the files when multiple folders are present

### ISSUE THREAD

**Issue by maskaravivek** [ab-anand/ZDrive#5]
First of all great job at building this utility. 

I am trying to download a folder which in turn contains multiple folders. When I run the code, the contents of just the first folder get downloaded. 

I took a look at the code and ideally, all the files in all the folders should have been downloaded but I guess the `Process` is messing up something. 

Eg. folder structure: 

- MNIST/
  - 1/
     - file1.jpg
     - file2.jpg 
  - 2/
     - file3.jpg
     - file4.jgp
  - 3/
     -  file5.jpg
     - file6.jpg

For the above structure, just files in MNIST/1/ get downloaded.

**Comment by ab-anand** [comment]
Hey, thanks for the contribution. I'm unable to reproduce it. I've tried to download 100s of files and it downloaded properly. May I know how much data are you dealing with?
