### ISSUE TITLE
Problems with recursion

### ISSUE THREAD

**Issue by Covvperwood** [ab-anand/ZDrive#8]
There are some problems with recursion. Script choose only first folder. If in folder 2 subfolders exist, only first will taken.

**Comment by blounsbury-usbr** [comment]
I had the same problem, but found a solution. I was going to submit a pull request, but don't have the time to step through it. Hopefully, the developers see this and can make this simple change.

Inside of downloader.py/getAllFiles, line 39 I changed:
* `q="parents in '{0}'".format(folderId)`

to:

* `q="'{0}' in parents".format(folderId)`

**Comment by ab-anand** [comment]
Thanks @blounsbury-usbr @Covvperwood for noticing and suggesting the fix. I've rolled out a new version with the change

**Comment by blounsbury-usbr** [comment]
Oops. Looks like your commit missed recursion fix the `q="'{0}' in parents".format(folderId)` line. Thanks for accepting the fixes!

**Comment by ab-anand** [comment]
My bad, updated it. Thanks @blounsbury-usbr
