### ISSUE TITLE
Cannot import name 'SIGPIPE' from 'signal' in windows

### ISSUE THREAD

**Issue by JackismyShephard** [ab-anand/ZDrive#9]
I am getting the error 

`cannot import name 'SIGPIPE' from 'signal' (C:\Users\Jacki\anaconda3\lib\signal.py)`

when running 

`from zdrive import Uploader`

on python 3.8.12 windows.

**Comment by zamzami16** [comment]
you can change the code from:

```
from signal import signal, SIGPIPE, SIG_DFL
signal(SIGPIPE, SIG_DFL)
```

into:

```
try:
    from signal import signal, SIGPIPE, SIG_DFL
    signal(SIGPIPE, SIG_DFL)
except ImportError:
    pass
```

**Comment by blounsbury-usbr** [comment]
Same issue here on Windows. I'm not tracking this solution. The error occurs at 'import zdrive', adding the try/except does not fix the zdrive import error.

**Comment by blounsbury-usbr** [comment]
> Same issue here on Windows. I'm not tracking this solution. The error occurs at 'import zdrive', adding the try/except does not fix the zdrive import error.

Ah, I see, put the try/except in the zdrive code. Got it!

Would be nice to place an IF windows statement in the zdrive code or some other workaround so the package works on Windows without user modification of zdrive code.

**Comment by ab-anand** [comment]
for now, i've used the try/except. Will update once there is any solid alternative for windows
